### ISSUE TITLE
Use tenv instead of tfenv

### ISSUE THREAD

**Issue by kvendingoldo** [ballerabdude/dotfiles#1]
Hi. Great repo! I see that you use tfenv here:

https://github.com/ballerabdude/dotfiles/blob/04a50b409ab3e5b7bafc36c88d9774b17bbe4bbf/install#L57

I suggest you to switch to tenv: https://github.com/tofuutils/tenv:

* it is a successor of [tofuenv](https://github.com/tofuutils/tofuenv) and [tfenv](https://github.com/tfutils/tfenv)
* can manage versions of OpenTofu / Terraform / Terragrunt and Atmos
* does not require any dependencies like jq / bash / etc

**Comment by ballerabdude** [comment]
Thanks for the suggestion. Once I run into an issue with tfenv I'll make the move.
